workflows:
  debug-apk:
    name: Debug APK
    environment:
      flutter: stable
      java: 17
      vars:
        ANDROID_SDK_ROOT: /usr/local/share/android-sdk
    scripts:
      - name: Install Android SDK 36 + Build-Tools 36
        script: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-36" "build-tools;36.0.0" "platform-tools"
      - name: Flutter packages
        script: |
          flutter --version
          flutter pub get
      - name: Build debug APK
        script: |
          flutter build apk --debug --verbose
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
