name: ride_my_way
description: Application Ride My Way
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  go_router: ^16.1.0

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  cloud_functions: ^5.6.2
  flutter_local_notifications: ^17.2.2
  firebase_messaging: ^15.0.4

  # Formulaires / permissions
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.7
  file_picker: ^10.2.1
  audio_session: ^0.2.2
  animated_text_kit: ^4.2.2

  # Géolocalisation
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.6.1

  # Autocomplétion
  google_places_flutter: ^2.1.0
  google_places_autocomplete_text_field: ^1.1.0

  # HTTP / API
  http: ^0.13.6
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_polyline_points: ^1.0.0

  # Outils
  equatable: ^2.0.5
  lucide_icons: ^0.257.0

  # Graphiques & animations
  fl_chart: ^1.0.0
  lottie: ^3.0.0
  animated_background: ^2.0.0
  flutter_animate: ^4.2.0
  animate_do: ^4.2.0
  diacritic: ^0.1.3
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.5
  just_audio: ^0.10.4

  # Paiement
  flutter_stripe: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon/icon.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/app_icon/icon.png
  remove_alpha_ios: true
  min_sdk_android: 24

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/notification.mp3
    - assets/sounds/success.mp3
    - assets/sounds/urgent_alert.mp3
    - assets/sounds/driver_found.mp3
    - assets/sounds/confirmed.mp3
    - assets/map_style_dark.json
    - assets/icons/car_gold.png
    - assets/images/user_placeholder.png
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic
