org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.enableJetifier=true

kotlin.incremental=true
kotlin.jvm.target=17
# ne pas utiliser kotlin.experimental.tryK2

flutter.compileSdkVersion=35
flutter.minSdkVersion=23
flutter.targetSdkVersion=35
