// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCun49hxFiWV7ux61kO9cj_8n1f7uhkn38',
    appId: '1:894264775353:web:f96aec2ece1488d1dc8168',
    messagingSenderId: '894264775353',
    projectId: 'ride-my-way-7f258',
    authDomain: 'ride-my-way-7f258.firebaseapp.com',
    storageBucket: 'ride-my-way-7f258.firebasestorage.app',
    measurementId: 'G-L125RZY539',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ4Luk0fahKqGUWxt1iTa826mhbGDB27k',
    appId: '1:894264775353:android:8867f62d4e5b7354dc8168',
    messagingSenderId: '894264775353',
    projectId: 'ride-my-way-7f258',
    storageBucket: 'ride-my-way-7f258.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOKDX1Gvq5IXpFGujCle-IyQItE4GW7cg',
    appId: '1:894264775353:ios:2ce19b765c329482dc8168',
    messagingSenderId: '894264775353',
    projectId: 'ride-my-way-7f258',
    storageBucket: 'ride-my-way-7f258.firebasestorage.app',
    iosBundleId: 'com.example.rideMyWay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOKDX1Gvq5IXpFGujCle-IyQItE4GW7cg',
    appId: '1:894264775353:ios:2ce19b765c329482dc8168',
    messagingSenderId: '894264775353',
    projectId: 'ride-my-way-7f258',
    storageBucket: 'ride-my-way-7f258.firebasestorage.app',
    iosBundleId: 'com.ridemyway.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCun49hxFiWV7ux61kO9cj_8n1f7uhkn38',
    appId: '1:894264775353:web:935419033f62e198dc8168',
    messagingSenderId: '894264775353',
    projectId: 'ride-my-way-7f258',
    authDomain: 'ride-my-way-7f258.firebaseapp.com',
    storageBucket: 'ride-my-way-7f258.firebasestorage.app',
    measurementId: 'G-499C714N1M',
  );
}
